name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@caa797cc7baec52e99f21b86f532a4b7c88cf4fa # fix/grype-install-outside-scan-path
    with:
      require-scope: false

  actionlint:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@caa797cc7baec52e99f21b86f532a4b7c88cf4fa # fix/grype-install-outside-scan-path
    with:
      working-directory: "."
