name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@01e2b12e992621fecf074b8a202f66044196f3bf # v1.0.4
    with:
      require-scope: false

  actionlint:
    permissions:
      contents: read
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@01e2b12e992621fecf074b8a202f66044196f3bf # v1.0.4
    with:
      working-directory: "."
