name: DevOps / PR Hygiene

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  semantic-pr:
    permissions:
      contents: read
      uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-semantic-pr.yml@3858e9e74c805067e454740b195372c7195f333b # v1.5.0
    with:
      require-scope: false

  actionlint:
    permissions:
      contents: read
      uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-actionlint.yml@3858e9e74c805067e454740b195372c7195f333b # v1.5.0
    with:
      working-directory: "."
