# Workflow: release-please for aggregator
# This workflow enables automatic releases using release-please for this workflow aggregator repo.

name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-please:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: FelipeFuhr/ffreis-workflows-general/.github/workflows/general-release-please.yml@caa797cc7baec52e99f21b86f532a4b7c88cf4fa # fix/grype-install-outside-scan-path
    with:
      dry-run: false
      config-file: .release-please-config.json
      manifest-file: .release-please-manifest.json
      target-branch: main
